name: AWS Connection Test
on:
  workflow_dispatch: # 수동 실행 가능하도록 설정

jobs:
  test-aws-connection:  # 이름 아무거나 설정
    runs-on: ubuntu-latest  # x86_64 우분투 환경에서 실행
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Test AWS CLI
        run: |
          aws sts get-caller-identity
          aws ecr describe-repositories --repository-names sb06/image-post
