name: Deploy Spring Boot App

on:
  workflow_dispatch:

# 자동 실행 설정
#  push:
#    branches:
#      - main
#      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5  # 이미 만들어진 액션 사용

      - name: Set up JDK 17
        uses: actions/setup-java@v5  # 이미 만들어진 액션 사용
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Compile and test with Gradle
        run: ./gradlew test

      - name: Build Docker image
        run: docker build -t image-post:latest .

      - name: Set environment variables for tagging
        run: |
          echo "ECR_REGISTRY=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com" >> $GITHUB_ENV
          echo "ECR_REPOSITORY=${{ secrets.AWS_ECR_REPOSITORY_NAME }}" >> $GITHUB_ENV
          echo "IMAGE_TAG=$(date +'%Y%m%d%H%M%S')-${GITHUB_SHA::8}" >> $GITHUB_ENV

# ECR_REGISTRY를 환경 변수로 설정
# ECR_REPOSITORY를 환경 변수로 설정
# IMAGE_TAG를 환경 변수로 설정 (날짜 + 커밋 해시)

      - name: Tag Docker image
        run: |
# 태그 중복 설정
          docker tag image-post:latest ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          docker tag image-post:latest ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest

# 접속 정보 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

# ECR 로그인
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

# 도커 이미지 푸시
      - name: Push Docker image to ECR
        run: |
          docker push ${{env.ECR_REGISTRY}}/${{env.ECR_REPOSITORY}}:${{env.IMAGE_TAG}}
          docker push ${{env.ECR_REGISTRY}}/${{env.ECR_REPOSITORY}}:latest


      - name: Download task definition template
        run: |
# 태스크 이름 image-post-app-td
          aws ecs describe-task-definition --task-definition image-post-app-td --query taskDefinition > task-definition.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
# 컨테이너 이름
          container-name: image-post
          image: ${{env.ECR_REGISTRY}}/${{env.ECR_REPOSITORY}}:${{env.IMAGE_TAG}}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{steps.render-task-def.outputs.task-definition}}
# 서비스 이름
          service: image-post-app-td-service-6gz02mpk
# 클러스터 이름
          cluster: MyserviceCluster
          wait-for-service-stability: true

# 검증
      - name: Verify deployment status
        run: |
          echo "Verifying deployment..."

# 클러스터 이름, 서비스 이름
          aws ecs describe-services --cluster MyserviceCluster --services image-post-app-td-service-6gz02mpk
               echo "Deployment seems stable."
